use ecommerce;
-- =====================================================
-- 1. SALES OPTIMIZATION
-- =====================================================

-- Q1. What is the total revenue generated by the business?
select sum(quantity * price_per_unit) as Total_Revenue
from order_details_ecommerce;

-- Q2. How does revenue trend month over month?
select date_format(oe.order_date, '%Y-%m') as Month, sum(ode.quantity * ode.price_per_unit) as Total_Revenue
from orders_ecommerce oe
left join order_details_ecommerce ode
	on oe.order_id = ode.order_id
group by Month
order by Month;

-- Q3. What is the Average Order Value (AOV)?
select sum(ode.quantity * ode.price_per_unit) as Total_Revenue, 
		count(distinct oe.order_id) as Total_Orders,
        round(sum(ode.quantity * ode.price_per_unit) / count(distinct oe.order_id),2) as Average_Order_Value
from orders_ecommerce oe
join order_details_ecommerce ode
	on oe.order_id = ode.order_id;


-- =====================================================
-- 2. CUSTOMER INSIGHTS
-- =====================================================

-- Q4. Who are the top 5 customers by total revenue?
select oe.customer_id, ce.name, sum(ode.quantity * ode.price_per_unit) as Total_Revenue
from orders_ecommerce oe
join order_details_ecommerce ode
	on oe.order_id = ode.order_id
join customers_ecommerce ce
	on oe.customer_id = ce.customer_id
group by oe.customer_id, ce.name
order by Total_Revenue desc
limit 5;

-- Q5. How many repeat customers have placed more than one order?
select ce.customer_id, ce.name, count(distinct oe.order_id) as Total_Orders
from customers_ecommerce ce
left join orders_ecommerce oe
	on ce.customer_id = oe.customer_id
group by ce.customer_id, ce.name
having count(oe.order_id) > 1;

-- Q6. What are the revenue segments of customers based on
--     their total revenue contribution?
with Cust_Info as 
(
	select ce.customer_id, ce.name, sum(ode.quantity * ode.price_per_unit) as Total_Revenue
    from customers_ecommerce ce
    join orders_ecommerce oe
		on ce.customer_id = oe.customer_id
	join order_details_ecommerce ode
		on oe.order_id = ode.order_id
	group by ce.customer_id, ce.name
)
select customer_id, name, Total_Revenue,
case
	when Total_Revenue > 10000 then 'High'
    when Total_Revenue between 5000 and 10000 then 'Medium'
    else 'Low'
end as Segment
from Cust_Info;

-- Q7. How much revenue comes from Repeat Customers versus
--      One-Time Customers?
with Cust_Info as
(
	select ce.customer_id, 	ce.name, count(distinct oe.order_id) as Total_Orders,
			sum(ode.quantity * ode.price_per_unit) as Total_Revenue
	from customers_ecommerce ce
	join orders_ecommerce oe
		on ce.customer_id = oe.customer_id
	join order_details_ecommerce ode
		on oe.order_id = ode.order_id
	group by ce.customer_id,
	ce.name
)
select sum(Total_Revenue) as Total_Revenue,
Customer_Type
from (
select customer_id, name, Total_Orders, Total_Revenue, 
case
	when Total_Orders > 1 then 'Repeat'
    else 'One-Time'
    end as Customer_Type
from Cust_Info
) as Customer_Info
group by Customer_Type;

-- =====================================================
-- 3. PRODUCT & CATEGORY ANALYSIS
-- =====================================================

-- Q8. What is the total revenue generated by each product?
select pe.product_id, pe.name, coalesce(sum(ode.quantity * ode.price_per_unit),0) as Total_Revenue
from product_ecommerce pe
left join order_details_ecommerce ode
	on pe.product_id = ode.product_id
group by pe.product_id, pe.name
order by Total_Revenue desc;

-- Q9. Which product categories generate the highest revenue?
select pe.category, sum(ode.quantity * ode.price_per_unit) as Total_Revenue
from product_ecommerce pe
join order_details_ecommerce ode
	on pe.product_id = ode.product_id
group by pe.category
order by Total_Revenue desc;

-- Q10. How do product categories compare in terms of total revenue,
--     quantity sold, and average selling price?
select pe.category, sum(ode.quantity * ode.price_per_unit) as Total_Revenue,
		sum(ode.quantity) as Total_Quantity_Sold, round(avg(ode.price_per_unit),2) as Average_Selling_Price
from product_ecommerce pe
join order_details_ecommerce ode
	on pe.product_id = ode.product_id
group by pe.category;

-- Q11. What is the weighted average selling price for each product category?
select pe.category, sum(ode.quantity * ode.price_per_unit) as Total_Revenue, sum(ode.quantity) as Total_Quantity,
		round(sum(ode.quantity * ode.price_per_unit) / sum(ode.quantity),2) as Weighted_Average_Selling_Price
from product_ecommerce pe
join order_details_ecommerce ode
	on pe.product_id = ode.product_id
group by pe.category;

-- Q12. Which products rank highest by total revenue, and what is
--      the revenue contribution of the top 5 products?
with Product_Revenue as 
(
	select pe.product_id, pe.name, sum(ode.quantity * ode.price_per_unit) as Total_Revenue,
			dense_rank() over (
			order by sum(ode.quantity * ode.price_per_unit) desc) as Rankings
	from product_ecommerce pe
	join order_details_ecommerce ode
		on pe.product_id = ode.product_id
	group by pe.name, pe.product_id
)
select 
	round(sum(case when Rankings <= 5 then Total_Revenue else 0 end),2) as Top_5_Revenue,
    round(sum(Total_Revenue),2) as Total_Revenue,
    round(sum(case when Rankings <= 5 then Total_Revenue else 0 end) / sum(Total_Revenue) * 100,2) as Top_5_Revenue_Percentage
from Product_Revenue;

